services:
  backend:
    build: ./backend
    ports:
    - "8000:8000"
    env_file:
    - .env

  frontend:
    build: ./frontend
    ports:
    - "8501:8501"
    environment:
    - DOCKER_ENV=true
    depends_on:
    - backend